[package]
name = "wasmedge_wasi_socket"
version = "0.1.0"
authors = [ "Yi <yi@secondstate.io>" ]
edition = "2018"

[lib]
name = "wasmedge_wasi_socket"
path = "src/lib.rs"

[features]
std = []

[dependencies]
libc = "0.2.3"

[workspace]
members = [
    "examples/http_client",
    "examples/http_server"
]