name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup cargo
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: build
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo build
        rustup target add wasm32-wasi
    - name: build examples
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo build --target=wasm32-wasi --examples
    - name: build examples with std
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo build --features std --examples
