name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup cargo
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: build
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        rustup target add wasm32-wasi
        cargo build
    - name: build examples on WASI
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo build --examples
    - name: build examples with std on x86_64
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo build --target=x86_64-unknown-linux-gnu --features std --examples
